name: "Owlix Connector"
version: "1.0.0"
slug: "owlix_connector"
description: "Connect your Home Assistant to Owlix Platform via Secure Tunnel"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
options:
  owlix_api_key: ""
schema:
  owlix_api_key: "str?"
host_network: true
